"""PPTX export service."""

from io import BytesIO

from pptx import Presentation
from pptx.util import Inches, Pt

from app.models.diagram import DiagramVersion


def create_pptx_export(diagram_id: str, version: DiagramVersion) -> bytes:
    """Create a simple one-slide PPTX for a diagram version."""

    presentation = Presentation()
    slide = presentation.slides.add_slide(presentation.slide_layouts[5])

    title = slide.shapes.title
    if title is not None:
        title.text = f"{version.engine_type} diagram"

    subtitle_box = slide.shapes.add_textbox(Inches(0.6), Inches(0.9), Inches(8.8), Inches(0.5))
    subtitle_frame = subtitle_box.text_frame
    subtitle_frame.text = f"Diagram {diagram_id} / Version {version.id}"
    subtitle_frame.paragraphs[0].font.size = Pt(12)

    concept_box = slide.shapes.add_textbox(Inches(0.6), Inches(1.35), Inches(8.8), Inches(0.8))
    concept_frame = concept_box.text_frame
    concept_frame.text = (version.design_concept or "Generated by SmartDiagram Agent Platform")[:320]
    concept_frame.paragraphs[0].font.size = Pt(11)

    code_box = slide.shapes.add_textbox(Inches(0.6), Inches(2.25), Inches(8.8), Inches(4.4))
    code_frame = code_box.text_frame
    code_frame.word_wrap = True
    code_frame.text = (version.code or "")[:3000]
    for paragraph in code_frame.paragraphs:
        paragraph.font.name = "Aptos Mono"
        paragraph.font.size = Pt(8)

    footer = slide.shapes.add_textbox(Inches(0.6), Inches(6.95), Inches(8.8), Inches(0.3))
    footer.text_frame.text = "SmartDiagram export artifact"
    footer.text_frame.paragraphs[0].font.size = Pt(9)

    output = BytesIO()
    presentation.save(output)
    return output.getvalue()
