import type { DesignRecipe } from "./types.js";

export const DESIGN_RECIPES: DesignRecipe[] = [
  {
    id: "dual-engine-bridge",
    label: "双引擎桥接",
    story: "两个能力系统通过中心枢纽汇聚成一个更高阶结论，适合‘A+B=新能力’。",
    useWhen: "正文恰好两个互补模块，主题包含融合、协同、双轮驱动、两类能力或从 A 到 B。",
    layoutHints: ["comparison", "two-column", "generic-cards", "architecture"],
    semanticTags: ["融合", "协同", "双", "两", "结合", "桥梁", "互补", "能力"],
    minBlocks: 2,
    maxBlocks: 2,
    zones: [
      { id: "title-zone", role: "title", x: 78, y: 62, w: 710, h: 112, layer: 30, instruction: "左对齐两级标题，关键词可拆色；右侧保留空气感和章节微标。" },
      { id: "key-message-zone", role: "key-message", x: 420, y: 176, w: 440, h: 68, layer: 35, instruction: "结论做成跨越左右系统的桥梁色带，不作为普通副标题。" },
      { id: "content-zone-1", role: "content", x: 78, y: 276, w: 448, h: 346, layer: 20, instruction: "左系统：层叠切角面板 + 圆章图形 + 3 条短证据。" },
      { id: "visual-anchor", role: "visual-anchor", x: 570, y: 326, w: 140, h: 210, layer: 40, instruction: "中心融合枢纽：同心圆、关键词、上下短轨道，承担全页视觉焦点。" },
      { id: "content-zone-2", role: "content", x: 754, y: 276, w: 448, h: 346, layer: 20, instruction: "右系统：与左侧同语法但轮廓/强调位不同，避免镜像复制。" },
      { id: "connector-layer", role: "connector", x: 490, y: 300, w: 300, h: 270, layer: 25, instruction: "两侧各 2 条曲线路径汇入中心，表达融合关系。" }
    ],
    backgroundProgram: ["柔色底 + 左右两块低透明度圆形光域", "叠加稀疏坐标点或水平基线，强调左右汇聚轴"],
    titleProgram: ["标题左对齐，不居中", "标题下用 72-120px 强调短线建立阅读起点"],
    keyMessageProgram: ["结论压缩为中心桥接梁或横向标签", "从结论中选 1 个输入已有关键词做强调色，禁止补词"],
    contentProgram: ["两个模块分别映射到左右系统", "每侧使用不同侧边色带/切角方向", "每条 item 配一个小几何符号或序号节点，不用普通 bullet 墙"],
    connectorProgram: ["path 从左右内容区指向 visual-anchor", "连接线端点用 circle 标记，中心汇聚线比外围线更粗"],
    signatureMotif: "中央圆形融合枢纽 + 左右双系统 + 跨栏结论桥",
    forbidden: ["两个同尺寸白色圆角卡片直接并排", "标题与结论全部居中", "用双向箭头图标代替完整关系结构"],
    requiredGroupIds: ["background-layer", "title-zone", "visual-anchor", "content-zone-1", "content-zone-2", "connector-layer"],
    requiredPrimitives: ["path", "circle"]
  },
  {
    id: "radial-ecosystem",
    label: "中心辐射生态",
    story: "以核心能力/平台为中心，外围模块形成系统关系和层级。",
    useWhen: "架构、能力图谱、Agent/平台生态、组件关系，且正文为 3-6 个模块。",
    layoutHints: ["architecture", "generic-cards", "radial", "capability-map"],
    semanticTags: ["架构", "系统", "生态", "平台", "组件", "Agent", "图谱", "核心"],
    minBlocks: 3,
    maxBlocks: 6,
    zones: [
      { id: "title-zone", role: "title", x: 70, y: 54, w: 600, h: 116, layer: 30, instruction: "左上编辑式标题，章节标签与短横线形成起点。" },
      { id: "key-message-zone", role: "key-message", x: 70, y: 170, w: 470, h: 78, layer: 30, instruction: "结论作为左侧导语块，与中心系统建立引导线。" },
      { id: "visual-anchor", role: "visual-anchor", x: 490, y: 220, w: 300, h: 300, layer: 40, instruction: "中心 2-3 层圆环/六边形，放核心关键词，不堆正文。" },
      { id: "content-zone-1", role: "content", x: 70, y: 286, w: 330, h: 150, layer: 20, instruction: "外围节点 1。" },
      { id: "content-zone-2", role: "content", x: 70, y: 470, w: 330, h: 150, layer: 20, instruction: "外围节点 2。" },
      { id: "content-zone-3", role: "content", x: 880, y: 214, w: 330, h: 126, layer: 20, instruction: "外围节点 3。" },
      { id: "content-zone-4", role: "content", x: 880, y: 370, w: 330, h: 126, layer: 20, instruction: "外围节点 4。" },
      { id: "content-zone-5", role: "content", x: 880, y: 526, w: 330, h: 110, layer: 20, instruction: "外围节点 5；没有第 5 块时留白。" },
      { id: "connector-layer", role: "connector", x: 360, y: 200, w: 560, h: 430, layer: 25, instruction: "用折线路径/曲线把外围节点接入中心。" }
    ],
    backgroundProgram: ["深浅两级底色 + 中心低透明度轨道圆", "可加稀疏网格点，但不能盖过文字"],
    titleProgram: ["左上标题区与系统图错位，不做居中封面"],
    keyMessageProgram: ["结论作为图例式导语或中心外环标签"],
    contentProgram: ["模块按重要度分配不同面积", "节点使用标签槽 + 1-3 条证据，至少一种节点采用非矩形轮廓"],
    connectorProgram: ["所有连接必须有起终点", "不同关系可用实线/虚线，但最多两种线型"],
    signatureMotif: "核心轨道 + 不对称外围节点 + 有意义连接线",
    forbidden: ["六张等宽卡片排成网格", "中心只放装饰图标", "线条穿过正文"],
    requiredGroupIds: ["background-layer", "title-zone", "visual-anchor", "content-zone-1", "content-zone-2", "content-zone-3", "connector-layer"],
    requiredPrimitives: ["circle", "path"]
  },
  {
    id: "stepped-roadmap",
    label: "阶梯路线图",
    story: "用高度、轨道和节点表达阶段递进，适合路径、步骤与时间进程。",
    useWhen: "时间线、流程、阶段、行动路径、从入门到进阶。",
    layoutHints: ["timeline", "process", "roadmap", "action-list"],
    semanticTags: ["路径", "步骤", "阶段", "时间", "路线", "行动", "进阶", "流程"],
    minBlocks: 2,
    maxBlocks: 6,
    zones: [
      { id: "title-zone", role: "title", x: 76, y: 56, w: 700, h: 106, layer: 30, instruction: "左上标题，与路线起点同轴。" },
      { id: "key-message-zone", role: "key-message", x: 800, y: 68, w: 390, h: 86, layer: 32, instruction: "右上结论标签，成为路线终点的方向说明。" },
      { id: "visual-anchor", role: "visual-anchor", x: 78, y: 210, w: 1120, h: 390, layer: 25, instruction: "折线路径自左下向右上推进，3-6 个节点随阶段抬升。" },
      { id: "content-zone-1", role: "content", x: 88, y: 420, w: 230, h: 176, layer: 30, instruction: "阶段 1 节点。" },
      { id: "content-zone-2", role: "content", x: 342, y: 350, w: 230, h: 176, layer: 30, instruction: "阶段 2 节点。" },
      { id: "content-zone-3", role: "content", x: 596, y: 280, w: 230, h: 176, layer: 30, instruction: "阶段 3 节点。" },
      { id: "content-zone-4", role: "content", x: 850, y: 210, w: 330, h: 176, layer: 30, instruction: "最终阶段节点，面积更大。" },
      { id: "connector-layer", role: "connector", x: 90, y: 260, w: 1060, h: 290, layer: 20, instruction: "阶梯折线/轨道连接各节点。" }
    ],
    backgroundProgram: ["底部起点深色块向右上逐渐打开", "用水平基线或稀疏刻度强化进度"],
    titleProgram: ["标题与起点对齐，不占据路线中心"],
    keyMessageProgram: ["放在终点附近作为方向旗标或结论牌"],
    contentProgram: ["每个 contentBlock 对应一个阶段", "阶段编号作为几何节点而非大段文字", "最后阶段面积和对比度最高"],
    connectorProgram: ["使用 polyline/path 贯穿所有阶段", "节点处以 circle + 短竖线固定位置"],
    signatureMotif: "从左下到右上的阶梯轨道",
    forbidden: ["横向四张等高卡片", "只有箭头没有阶段层级", "伪造时间或百分比"],
    requiredGroupIds: ["background-layer", "title-zone", "visual-anchor", "content-zone-1", "content-zone-2", "connector-layer"],
    requiredPrimitives: ["polyline", "circle"]
  },
  {
    id: "evidence-dashboard",
    label: "证据型数据叙事",
    story: "用一个主指标或主图形带动若干证据模块，强调洞察而不是后台仪表盘。",
    useWhen: "有真实指标、趋势、图表或强调数据。",
    layoutHints: ["metrics", "chart", "dashboard", "data"],
    semanticTags: ["指标", "数据", "增长", "趋势", "占比", "规模", "结果", "验证"],
    minBlocks: 1,
    maxBlocks: 5,
    zones: [
      { id: "title-zone", role: "title", x: 70, y: 54, w: 760, h: 108, layer: 30, instruction: "左上标题，右上保留数据口径标签。" },
      { id: "key-message-zone", role: "key-message", x: 70, y: 172, w: 420, h: 100, layer: 32, instruction: "结论作为左侧洞察短文，不重复图表标题。" },
      { id: "visual-anchor", role: "visual-anchor", x: 500, y: 170, w: 710, h: 310, layer: 25, instruction: "主图表/主指标，占全页最大面积。" },
      { id: "content-zone-1", role: "content", x: 70, y: 302, w: 390, h: 304, layer: 25, instruction: "主证据解释块，允许大关键词或真实数字。" },
      { id: "content-zone-2", role: "content", x: 500, y: 510, w: 335, h: 112, layer: 25, instruction: "证据条 2。" },
      { id: "content-zone-3", role: "content", x: 864, y: 510, w: 346, h: 112, layer: 25, instruction: "证据条 3。" }
    ],
    backgroundProgram: ["干净数据画布，图表区用轻微色域分区", "只保留一种坐标/网格语法"],
    titleProgram: ["标题和数据口径分离；不制造日期或来源"],
    keyMessageProgram: ["结论紧邻主图表起点，形成先结论后证据"],
    contentProgram: ["最大区域必须是数据图形而非卡片", "无真实数值时改用关系图，绝不生成伪刻度"],
    connectorProgram: ["用引导线将关键点与对应解释连接"],
    signatureMotif: "大图表 + 洞察边栏 + 证据条",
    forbidden: ["四个 KPI 卡片组成后台仪表盘", "伪造百分比", "图表与结论互不对应"],
    requiredGroupIds: ["background-layer", "title-zone", "visual-anchor", "content-zone-1"],
    requiredPrimitives: ["path", "line"]
  },
  {
    id: "matrix-contrast",
    label: "对照矩阵",
    story: "围绕明确比较轴展示差异、权衡与选择。",
    useWhen: "对比、优劣、现状与目标、方案选择、矩阵或表格。",
    layoutHints: ["comparison", "table", "matrix"],
    semanticTags: ["对比", "区别", "现状", "目标", "优劣", "方案", "选择", "矩阵"],
    minBlocks: 2,
    maxBlocks: 4,
    zones: [
      { id: "title-zone", role: "title", x: 70, y: 52, w: 720, h: 104, layer: 30, instruction: "标题左对齐。" },
      { id: "key-message-zone", role: "key-message", x: 820, y: 58, w: 390, h: 92, layer: 32, instruction: "右上结论强调块。" },
      { id: "visual-anchor", role: "visual-anchor", x: 70, y: 194, w: 1140, h: 420, layer: 20, instruction: "中轴或 2x2 对照矩阵，主选项突出。" },
      { id: "content-zone-1", role: "content", x: 98, y: 228, w: 500, h: 340, layer: 25, instruction: "对照侧 A。" },
      { id: "content-zone-2", role: "content", x: 682, y: 228, w: 500, h: 340, layer: 25, instruction: "对照侧 B。" },
      { id: "connector-layer", role: "connector", x: 604, y: 220, w: 72, h: 360, layer: 30, instruction: "中轴、差异标记或方向符号。" }
    ],
    backgroundProgram: ["左右使用同一色系不同明度，选中侧用强调色", "中轴保持高对比"],
    titleProgram: ["左对齐，必要时加入小型比较维度标签"],
    keyMessageProgram: ["作为选择结论或取舍原则，不悬空"],
    contentProgram: ["对应条目水平对齐", "每侧轮廓不同，避免两个白卡复制", "只突出真正差异"],
    connectorProgram: ["中轴用 line/path 标出关系，必要时使用少量箭头"],
    signatureMotif: "高对比中轴 + 两侧不同材质面板",
    forbidden: ["两个完全相同的白卡片", "所有条目都高亮", "没有比较维度"],
    requiredGroupIds: ["background-layer", "title-zone", "visual-anchor", "content-zone-1", "content-zone-2", "connector-layer"],
    requiredPrimitives: ["line", "polygon"]
  },
  {
    id: "editorial-hero-split",
    label: "编辑式主视觉分栏",
    story: "强标题与一个抽象主视觉形成不对称分栏，适合封面、章节和观点页。",
    useWhen: "封面、章节过渡、核心观点、内容较少。",
    layoutHints: ["cover", "statement", "transition", "closing"],
    semanticTags: ["指南", "愿景", "结论", "主题", "开场", "未来"],
    minBlocks: 0,
    maxBlocks: 2,
    zones: [
      { id: "title-zone", role: "title", x: 76, y: 104, w: 650, h: 240, layer: 35, instruction: "左侧超大标题，最多 3 行，形成整页最强字阶。" },
      { id: "key-message-zone", role: "key-message", x: 80, y: 382, w: 520, h: 112, layer: 35, instruction: "标题下方结论色带/短文块。" },
      { id: "visual-anchor", role: "visual-anchor", x: 716, y: 72, w: 500, h: 560, layer: 25, instruction: "右侧抽象图形系统：轨道、巨型字母轮廓或模块化图腾。" },
      { id: "content-zone-1", role: "content", x: 80, y: 534, w: 510, h: 88, layer: 30, instruction: "可选底部证据/章节标签，不足则留白。" }
    ],
    backgroundProgram: ["大面积底色 + 右侧 30%-40% 强色域", "加入一条贯穿分栏的细线或巨型透明编号"],
    titleProgram: ["标题字阶 54-76px，左对齐", "允许关键词断行形成形状，不做普通居中标题"],
    keyMessageProgram: ["用强调色带或细边框短文块承载，不做居中副标题"],
    contentProgram: ["内容极少时主动留白", "可把一个模块做成底部证据条，禁止补齐卡片"],
    connectorProgram: ["用一条基准线连接文字区与主视觉"],
    signatureMotif: "左侧超大字阶 + 右侧抽象图腾",
    forbidden: ["标题水平居中", "封面底部摆三张无意义卡片", "用正文填满留白"],
    requiredGroupIds: ["background-layer", "title-zone", "visual-anchor"],
    requiredPrimitives: ["path", "circle"]
  },
  {
    id: "asymmetric-card-stack",
    label: "不对称信息栈",
    story: "一个主模块带动若干次级模块，通过面积、色块和错位形成层级。",
    useWhen: "3-5 个分类/要点且没有明确流程、数据或架构关系。",
    layoutHints: ["generic-cards", "bento", "content"],
    semanticTags: ["分类", "要点", "能力", "维度", "原则", "方法"],
    minBlocks: 3,
    maxBlocks: 5,
    zones: [
      { id: "title-zone", role: "title", x: 72, y: 54, w: 670, h: 108, layer: 35, instruction: "左上标题。" },
      { id: "key-message-zone", role: "key-message", x: 780, y: 60, w: 430, h: 100, layer: 35, instruction: "右上结论块。" },
      { id: "visual-anchor", role: "visual-anchor", x: 72, y: 196, w: 560, h: 420, layer: 25, instruction: "主模块，占正文 45%-55% 面积，包含抽象图形或大关键词。" },
      { id: "content-zone-1", role: "content", x: 72, y: 196, w: 560, h: 420, layer: 30, instruction: "最重要内容块，层叠面板。" },
      { id: "content-zone-2", role: "content", x: 668, y: 196, w: 542, h: 188, layer: 30, instruction: "次级宽卡。" },
      { id: "content-zone-3", role: "content", x: 668, y: 420, w: 250, h: 196, layer: 30, instruction: "次级小卡。" },
      { id: "content-zone-4", role: "content", x: 954, y: 420, w: 256, h: 196, layer: 30, instruction: "次级小卡。" }
    ],
    backgroundProgram: ["柔色底 + 主模块背后错位色片", "用一条竖向或斜向视觉轴组织信息"],
    titleProgram: ["标题与主模块左边界对齐"],
    keyMessageProgram: ["放在右上独立强调区，与主模块形成对角关系"],
    contentProgram: ["第一模块必须明显大于其他模块", "至少两种轮廓/填色处理", "小模块只保留标题和 1-2 条证据"],
    connectorProgram: ["分类型页面可不用显式连线，用色带和编号建立组关系"],
    signatureMotif: "一大两小的错位信息栈",
    forbidden: ["四张等宽等高卡片", "每块使用完全相同的标题和 bullet 样式", "标题居中"],
    requiredGroupIds: ["background-layer", "title-zone", "visual-anchor", "content-zone-1", "content-zone-2", "content-zone-3"],
    requiredPrimitives: ["polygon"]
  },
  {
    id: "quote-monument",
    label: "纪念碑式观点页",
    story: "把唯一结论做成可记忆的视觉句子，少量证据退到边缘。",
    useWhen: "金句、总结、章节收束或单一强观点。",
    layoutHints: ["statement", "closing"],
    semanticTags: ["总结", "结论", "关键", "本质", "一句话"],
    minBlocks: 0,
    maxBlocks: 2,
    zones: [
      { id: "title-zone", role: "title", x: 78, y: 60, w: 430, h: 82, layer: 30, instruction: "小标题退居左上。" },
      { id: "key-message-zone", role: "key-message", x: 178, y: 210, w: 924, h: 250, layer: 40, instruction: "核心结论成为 48-68px 的主视觉文字块。" },
      { id: "visual-anchor", role: "visual-anchor", x: 110, y: 160, w: 1060, h: 390, layer: 25, instruction: "巨型引号/框线/圆弧构成纪念碑轮廓。" },
      { id: "content-zone-1", role: "content", x: 180, y: 526, w: 920, h: 88, layer: 30, instruction: "可选证据条；没有则保持留白。" }
    ],
    backgroundProgram: ["单色或双色大色域，装饰极少", "一个巨型透明字符或圆弧建立尺度"],
    titleProgram: ["标题小而克制，让位给结论"],
    keyMessageProgram: ["结论拆成 2-4 行，关键词单独着色", "不重复标题"],
    contentProgram: ["只允许一条证据带，不足则留白"],
    connectorProgram: ["不需要网络状连接线"],
    signatureMotif: "巨型结论 + 纪念碑框架",
    forbidden: ["把金句拆成三张卡", "补写解释段落", "使用花哨引号图片"],
    requiredGroupIds: ["background-layer", "title-zone", "visual-anchor"],
    requiredPrimitives: ["path"]
  }
];

export function getDesignRecipe(id: string) {
  return DESIGN_RECIPES.find((recipe) => recipe.id === id) ?? DESIGN_RECIPES.find((recipe) => recipe.id === "asymmetric-card-stack")!;
}

